[package]
name = "desktop"
version = "0.1.0"
edition = "2024"
default-run = "desktop"

[dependencies]
sysinfo = "0.37.2"
tokio = {version = "1.49.0", features = ["full"]}
freedesktop-file-parser = "0.3.1"

[features]
error = []